artnexp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<article_id>\d+)/$', views.detail, name='detail'),
]

artnexp/models.py
from django.db import models



class Author(models.Model):
    firstname=models.CharField(max_length=200)
    lastname=models.CharField(max_length=200)
    email=models.EmailField(blank=True)
    university = models.CharField(max_length=100,blank=True)
    web_address = models.URLField(blank=True)
    
    def __str__(self):
        return self.firstname+" "+self.lastname
    class Meta:
        ordering = ['lastname']

class Article(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField()
    article=models.FileField(upload_to="articles",blank=True)
    conference=models.CharField(max_length=200)

    def __str__(self):
        return self.title

class Authored(models.Model):
    AUTHOR_NO = ((1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6"), (7,
        "7"),(8,"8"),(9,"9"),(10,"10+"))

    author = models.ForeignKey(Author)
    article = models.ForeignKey(Article)
    author_ord = models.IntegerField(choices=AUTHOR_NO,verbose_name="Order")

    class Meta:
        ordering = ['author_ord']
        verbose_name = "Ordered Author"



class Experiment(models.Model):
    title=models.CharField(max_length=200)
    sections=models.CharField(max_length=200,blank=True)
    archive=models.FileField(upload_to="experiments",blank=True)
    description=models.TextField(blank=True)
    requirements=models.TextField(blank=True)
    howto=models.TextField(blank=True)
    article=models.ForeignKey(Article)

    def __str__(self):
        return self.title

class Publication(models.Model):
    PUBLICATIONS=(
            ('1', 'Unpublished'),
            ('2', 'Conference'),
            ('3', 'Journal'),
            ('4', 'Technical Report'),
            ('5', 'Other')
            )
    STATUS=(
            ('1', 'Unpublished'),
            ('2', 'Published'),
            ('3', 'Accepted'),
            ('4', 'Submitted'),
            ('5', 'Other')
            )
    pubtype=models.CharField(max_length=1,choices=PUBLICATIONS,default='1')
    pubstatus=models.CharField(max_length=1,choices=STATUS,default='1',blank=True)
    name=models.CharField(max_length=200,blank=True)
    url=models.URLField(blank=True)
    more=models.CharField(max_length=200,blank=True)
    date=models.DateField(blank=True)
    article=models.OneToOneField(Article)

    def __str__(self):
        return self.name

artnexp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import Article
# Create your views here.


def index(request):
     article_list = Article.objects.order_by('-id')

     context = {
        'article_list' : article_list,
     }
     return render(request, 'artnexp/index.html', context)
 

def detail(request, article_id):
     article=get_object_or_404(Article, pk=article_id)
     context = {
        'article' : article,
     }
     return render(request, 'artnexp/detail.html', context)

artnexp/templates/artnexp/artnexp_base.html
{% extends "base.html" %}
{% load static %}

{% block localcss %}
<link rel="stylesheet" type="text/css" href= "{% static "css/artnexp.css" %}">
{% endblock %}

{% block app_base %}
{% load staticfiles %}
    <div class="container content">
  {% block app_content %} {% endblock %}
  </div>
{% endblock %}

artnexp/templates/artnexp/detail.html
{% extends 'artnexp/artnexp_base.html' %}
{% block title %}
{{ article.title  }}
{% endblock %}
{% block app_content %}
{% load markdown_deux_tags %}
<h2>{{ article.title  }}</h2>
<hr></hr>
<div class="author"><span class="text-muted">{% for author in article.authors.all %}
  {{ author.firstname }} {{ author.lastname }}, 
  {% endfor %}</span></div> 
<div class="conference"><span class="text-muted">{{ article.publication.name }}
    {{ article.publication.date }}</span></div> 
<a href="{% url "artnexp:index" %}">Back to article list</a>
<h3>Abstract</h3>
{{ article.description|markdown }}
{% if article.publication.pubtype != '1' and article.publication.pubstatus == '2' and article.article %}
<div class="download"> <button type="button" class="btn btn-default"
                                            onClick='location.href="../../../media/{{ article.article.name }}"'>
    
    <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
    Download Article</button></div>
{% endif %}
{% if article.experiment_set.all %}
<div class="toc">
<h3>Table of Contents</h3>
    {% for exp  in article.experiment_set.all %}
    <ul>
      <li><a href="#exp{{ forloop.counter}}">Experiment {{ forloop.counter }}: {{ exp.title }}</a></li>
    </ul>
    {% endfor %}
    </div>
{% endif %}

{% if article.experiment_set.all %}
    {% for exp  in article.experiment_set.all %}

    <h2><a name="exp{{ forloop.counter}}">Experiment {{ forloop.counter }}: {{ exp.title }}</a></h2>
    <h3>Description</h3>
    {{ exp.description|markdown }}
    {% if exp.archive %}
<button type="button" class="btn btn-default" onClick='location.href="../../../media/{{ exp.archive.name }}"'>
  
    <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
  Download Archive</button>
{% endif %}
    <h3>Requirements</h3>
    {{ exp.requirements|markdown }}
    <h3>HowTo</h3>
    {{ exp.howto|markdown }}
    {% endfor %}
{% else %}
<h3>Table of Contents</h3>
<p>No Experiment at the moment</p>
{% endif %}

<a href="{% url "artnexp:index" %}">Back to article list</a>
{% endblock %}

artnexp/templates/artnexp/index.html
{% extends 'artnexp/artnexp_base.html' %}
{% block title %}
Publications
{% endblock %}
{% block app_content %}
<h2>Publications</h2>
<table class="table borderless" border="0">
  <tr>
  <td>
{% for article in article_list.all %}
<p><span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>{% for authored in article.authored_set.all %}
  {% if forloop.last %}
  and
  {% elif not forloop.first %}
  ,
  {% endif %}
  {{ authored.author.firstname }} {{ authored.author.lastname }}

  {% endfor %} --
  <a href='{% url "artnexp:detail" article.id %}'>{{ article.title }}</a> -- 
  
{% if article.publication.pubstatus == '1' %}
  Unpublished</p>

{% elif article.publication.pubstatus == '2' %}
  {{ article.publication.name }} -- {{ article.publication.date }} </p>
{% elif article.publication.pubstatus == '3' %}
<span class="text-muted"> Accepted at</span> {{ article.publication.name }} -- {{ article.publication.date }} </p>
{% elif article.publication.pubstatus == '4' %}
<span class="text-muted"> Submitted at</span> {{ article.publication.name }} -- {{ article.publication.date }} </p>
{% else %}
<span class="text-muted">Other </span> </p>
{% endif %}
{% endfor %}
</td>
</tr>
</table>
{% endblock %}